#  ____  _            _    ______  __  __          _              __   ___
# |  _ \| |          | |  |  ____|/ _|/ _|        | |            /_ | |__ \
# | |_) | | ___   ___| | _| |__  | |_| |_ ___  ___| |_ ___  __   _| |    ) |
# |  _ <| |/ _ \ / __| |/ /  __| |  _|  _/ _ \/ __| __/ __| \ \ / / |   / /
# | |_) | | (_) | (__|   <| |____| | | ||  __/ (__| |_\__ \  \ V /| |_ / /_
# |____/|_|\___/ \___|_|\_\______|_| |_| \___|\___|\__|___/   \_/ |_(_)____|
#               Activate special effects on block events!
#                         Coded by duplxey
#
# ==========================================================================
#                              Template
# ==========================================================================
# Copy the following template and fill in the data in order to create a new
# EBlock. Each block needs to have the fields tagged with '*'. The other ones
# are optional.
#
# <name>* - custom name (doesn't affect anything in game)
# <material>* - block material (Material: http://tinyurl.com/spigot-material)
# <trigger-type>* - how the block is triggered (WALK, WALK_INSIDE, LEFT_CLICK, RIGHT_CLICK, BREAK, PLACE)
# <message> - custom message sent to the player
# <permission> - allows only the player's with the given permission to use the block
# <potion-effect> - potion effect type (http://tinyurl.com/spigot-potioneffect)
# <potion-duration> - time in seconds
# <potion-amplifier> - potion amplifier
#
#  <name>:
#    material: <material>
#    trigger: <trigger-type>
#    message: <message>
#    permission: <permission>
#    effect:
#      type: <potion-effect>
#      duration: <potion-duration>
#      amplifier: <potion-amplifier>
#    commands:
#      - "<command1>"
#      - "<command2>"
#      - "<command3>"

# ==========================================================================
#                              EBlocks
# ==========================================================================
blocks:
  heal-block:
    material: REDSTONE_BLOCK
    trigger: RIGHT_CLICK
    message: "&6[BlockEffects] &cRegenerating your health!"
    effect:
      type: REGENERATION
      duration: 25
      amplifier: 2
    permission: blockeffects.redstone_block
  blindness-block:
    material: COAL_BLOCK
    trigger: WALK
    message: "&6[BlockEffects] &7You are now blind!"
    effect:
      type: BLINDNESS
      duration: 10
      amplifier: 1
    commands:
      - "say %player% has stepped on a coal_block,"
      - "say he is now blind!"

# ==========================================================================
#                              Security
# ==========================================================================
# Highly recommended to be enabled if you don't want to get spammed with
# effects & messages.
#
# enabled - boolean that enables/disables the security
# cooldown - cooldown time (in seconds) when you step on an EBlock
security:
  enabled: true
  cooldown: 1

# If enabled player will receive a message when he doesn't have the permission
# to activate an EBlock.
no-permission:
  send: true

# ==========================================================================
#                              World
# ==========================================================================
# List of the worlds in which the BlockEffects are going to work.
enabled-worlds:
  - "world"